name: "Extrae info de un pull request, IV/CC/ÁgilGRX"
description: "Mira un PR y extrae URL, usuario y nombre del repo, así como fichero modificado y objetivo"
outputs:
  user:
    description: "Usuario que creó el PR y del repo añadido"
  repo:
    description: "ID del repositorio que se ha añadido al PR"
  rama:
    description: "Rama del proyecto incluida en el PR"
  URL:
    description: "URL del repo a comprobar completo"
  file:
    description: "Fichero modificado en el PR"
  objetivo:
    description: "Objetivo al que corresponde el PR"
  checkout_repo:
    description: "Repo sobre el que se van a hacer los análisis"
  pr_milestone:
    description: "Milestone al que está asociado el PR"
  pull_number:
    description: "Número del PR en el repo"
runs:
  using: "node20"
  main: "dist/index.js"
