name: "Extrae info de un pull request, IV/CC/ÁgilGRX"
description: "Mira un PR y extrae URL, usuario y nombre del repo, así como fichero modificado y objetivo"
outputs:
  user:
    description: "Usuario que creó el PR y del repo añadido"
  repo:
    description: "ID del repositorio que se ha añadido al PR"
  rama:
    description: "Rama del proyecto incluida en el PR"
  URL:
    description: "URL del repo a comprobar completo"
  file:
    description: "Fichero modificado en el PR"
  objetivo:
    description: "Objetivo al que corresponde el PR"
runs:
  using: "node12"
  main: "dist/index.js"
